### ISSUE TITLE
What is this API about?

### ISSUE THREAD

**Issue by NathanPB** [wnull/warface-sdk#2]
Sorry, I see you didn't wrote a README yet and I didn't really had enough time to inspect the source code to figure it out by myself.

But I'd like to know if the project that you are developing here is about retrieving player data from the Warface HTTP API, or about injecting into the game client and listening to events like player kill, hit register, and so on.

I'm asking this because I'm interested in starting a project to collect player match statistics (kills, kill time, map position, frag, shooting accuracy) to try to make a big data tool to analyze and discuss competitive strategies. Does this wrapper do what I need?

**Comment by hyperplural** [comment]
@NathanPB, hi! Sadly, no. ​This is just a surface shell of data. My project is the implementation of public methods. For such an idea, you should look in the direction of [warfacebot](https://github.com/levak/warfacebot). There, the client is authorized to the server without the game itself. 

But, as far as I know, a new authorization path has been added to the game, and this project has stopped supporting it in terms of development, and is only engaged in updating keys. Such authorization was added in order to exclude all bots (whether for collecting statistics, or for launching players).

**Comment by wnull** [comment]
By the way, now on the API side of the game there is a problem in obtaining data. It's been ~2 months now. If there is a repeated request to the method without changing one of the parameters, the server returns an empty object. This is solved if you wait a few minutes, then the data will be displayed correctly (the database cache seems to be involved). This behavior is very strange, and it seems like the information has been passed to the developers.

It is also important to know when working with the game API that after the 100th request, the server stops giving a response (timeout). The fact is that there is a binding to the IP address. And to work correctly with numerous requests, you have to use a proxy. This is very problematic.

I hope I helped you in finding a solution :)

**Comment by hyperplural** [comment]
By the way, now on the API side of the game there is a problem in obtaining data. It's been ~2 months now. If there is a repeated request to the method without changing one of the parameters, the server returns an empty object. This is solved if you wait a few minutes, then the data will be displayed correctly (the database cache seems to be involved). This behavior is very strange, and it seems like the information has been passed to the developers.

It is also important to know when working with the game API that after the 100th request, the server stops giving a response (timeout). The fact is that there is a binding to the IP-address. And to work correctly with numerous requests, you have to use a proxy. This is very problematic.

I hope I helped you in finding a solution :)

**Comment by hyperplural** [comment]
> What is this API about? 

[The list of methods that are implemented here.](https://ru.warface.com/wiki/index.php/API)

Branches and methods:
1. Achievement 
- `catalog()` - gets achievement data
2. Clan
- `members()` - gets information about the members of clan
3. Game
- `missions()` - gets a list of current PVE-missions.
4. Rating
- `top100()` - gets information about the TOP100 rating 
- `monthly()` - gets information about the monthly (clans) rating
- `clan()` - gets information about the clans rating
5. User
- `stat()` - gets information about the user
- `achievement()` - gets information about the user achievements
6. Weapon
- `achievement()` - gets weapons data

**Comment by NathanPB** [comment]
Thank you so much, btw, I find that my problem will work better with an Nvidia API that is available for the Overwolf platform, still doing some research, but I think this guy made a pretty good job: https://github.com/Nathan-Schwartz/WarShadow

I was looking into the warfacebot repository you mentioned when I was studying the cases of a cheat that I found people using that was able to start rooms with maps and game modes that were not available. It was cool when a low ranked player joined the room and changed to Battle Royale maps, so everyone could play it
